# Exported from Render on 2025-12-22T05:47:23Z
version: "1"
services:
- type: web
  name: mockker/
  runtime: docker
  repo: https://github.com/prathamkhobragade05/springboot_mockker
  plan: free
  envVars:
  - key: SENDGRID_API
    sync: false
  - key: PORT
    sync: false
  - key: MAIL_USERNAME
    sync: false
  - key: MAIL_PORT
    sync: false
  - key: MAIL_PASSWORD
    sync: false
  - key: MAIL_HOST
    sync: false
  - key: DB_USERNAME
    sync: false
  - key: DB_URL
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: APP_NAME
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
