spring:
  application:
    name: Mockker

  datasource:
    url: jdbc:mysql://localhost:3306/mockker
    username: root
    password: 050902
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
 
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailservice.softara@gmail.com
    password: dmqb stxx lkpf mcwa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
 jwt:
  access-secret: my_access_token_secret_key
  refresh-secret: my_refresh_token_secret_key
  access-expiration: 3600000          # 1 hour
  refresh-expiration: 2592000000      # 30 days
  
server:
  port: 8080

